# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tracks_visits}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["grimen@gmail.com"]
  s.date = %q{2009-08-31}
  s.description = %q{Rails: Track unique and total visits/viewings of an ActiveRecord resource based on user/account or IP.}
  s.email = %q{Jonas Grimfelt}
  s.extra_rdoc_files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "lib/tracks_visits.rb",
     "lib/tracks_visits/tracks_visits_error.rb",
     "lib/tracks_visits/visit.rb",
     "lib/tracks_visits/visitable.rb",
     "lib/tracks_visits/visitor.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/tracks_visits_test.rb"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "lib/tracks_visits.rb",
     "lib/tracks_visits/tracks_visits_error.rb",
     "lib/tracks_visits/visit.rb",
     "lib/tracks_visits/visitable.rb",
     "lib/tracks_visits/visitor.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/tracks_visits_test.rb"
  ]
  s.homepage = %q{http://github.com/grimen/tracks_visits/tree/master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Rails: Track unique and total visits/viewings of an ActiveRecord resource based on user/account or IP.}
  s.test_files = [
    "test/test_helper.rb",
     "test/tracks_visits_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
